"""init db

Revision ID: 8062e9690eb9
Revises: 
Create Date: 2021-05-30 06:08:15.647533

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8062e9690eb9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('short_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('link', sa.String(length=2048), nullable=False),
    sa.Column('short_name', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_short_links_short_name'), 'short_links', ['short_name'], unique=True)
    op.create_table('short_links_redirects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('link_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['link_id'], ['short_links.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('short_links_redirects')
    op.drop_index(op.f('ix_short_links_short_name'), table_name='short_links')
    op.drop_table('short_links')
    # ### end Alembic commands ###
